# -*- coding: utf-8 -*-
"""cie1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1az2U0DpIVVYoff3QoWZ8IvQMRUY211n4
"""

import pandas as pd
a=pd.Series([1,2,3,4,5])
b=pd.Series([4,5,9,7,8])
result=a[~a.isin(b)]
result1=b[~b.isin(a)]
print(result)
print(result1)

import pandas as pd
a=pd.Series([1,2,3,4,5])
b=pd.Series([4,5,9,7,8])
result=a[a.isin(b)]
result1=b[b.isin(a)]
print(result)
print(result1)

import pandas as pd
a=pd.Series([1,2,3,4,5])
b=pd.Series([4,5,9,7,8])
print(a.min())
print(a.max())
print(b.sum())
print(b.median())
average=sum(a)/len(b)
print(average)

import pandas as pd
data=pd.read_csv("/content/tips.csv")
print(data)

filter_df=data[data['size']<2]
print(filter_df)

from functools import reduce
data=reduce(lambda x,y:x+y,data['total_bill'])
print(data)

data = data[(data['sex']=='Female')&(data['smoker']=='Yes')]
print(data)

number_of_tips=data['size'].value_counts()
print(number_of_tips)

avg_tip_by_day = data.groupby('day')['tip'].mean().reset_index()
print(avg_tip_by_day)

import matplotlib.pyplot as plt
plt.bar(avg_tip_by_day['Day'], avg_tip_by_day['tip'],color='pink',edgecolor='skyblue')
plt.xlabel('day')
plt.ylabel('tip')
plt.title('Total Tip by Day')
plt.show()

import matplotlib.pyplot as plt
plt.plot(avg_tip_by_day['day'], avg_tip_by_day['tip'],marker='v',linestyle='--',color='m')
plt.xlabel('day')
plt.ylabel('tip')
plt.title('Total Tip by Day')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
plt.scatter(avg_tip_by_day['day'], avg_tip_by_day['tip'],color='red',edgecolor='skyblue')
plt.xlabel('day')
plt.ylabel('tip')
plt.title('Total Tip by Day')
plt.grid(True)
plt.show()

import pandas as pd
data=pd.DataFrame({'product_id' :[1,2,3,4],
                   'items' :['panipuri','milk','biscuits','chips'],
                   'product_quantity' :[20,12,30,40],
                   'price' :[20,50,90,70]})
print(data)

pivot_price=data.pivot_table(values='price',index='items')
print(pivot_price)

pivot_table = data.pivot_table(values="total_revenue", index="price")
print(pivot_table)

import pandas as pd
data=pd.read_csv("/content/tips.csv")
print(data)

avg_tip_by_day = data.groupby('day')['tip'].sum()
print(avg_tip_by_day)

import matplotlib.pyplot as plt
bill=data.groupby('day')['total_bill'].sum()
bill.plot(kind='barh',color='pink')
plt.xlabel('Day')
plt.ylabel('Tip')
plt.title('Total Tip by Day')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(.csv)
sns.scatterplot(x='day',y='tip',data=df,alpha=0.7)
plt.xlabel('day')
plt.ylabel('tip')
plt.title('Total Tip by Day')
plt.grid(True)
plt.show()